"use client";
import { FormEvent, useMemo, useState } from "react";
import { Award, Plus, Trash2 } from "lucide-react";

type Certification={id:string;name:string;issuer:string;status:string;progress:number;issueDate:string|null;expiryDate:string|null;credentialUrl:string|null;skills:string[]};
export function CertificationManager({initial}:{initial:Certification[]}){
 const [items,setItems]=useState(initial); const [message,setMessage]=useState(''); const average=useMemo(()=>items.length?Math.round(items.reduce((s,i)=>s+i.progress,0)/items.length):0,[items]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage('');const form=new FormData(e.currentTarget);const payload={name:form.get('name'),issuer:form.get('issuer'),status:form.get('status'),progress:Number(form.get('progress')||0),issueDate:null,expiryDate:form.get('expiryDate')||null,credentialUrl:'',skills:String(form.get('skills')||'').split(',').map(v=>v.trim()).filter(Boolean)};const r=await fetch('/api/certifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok){setMessage(b.error||'Could not add certification');return}setItems(v=>[{...b.data,issueDate:b.data.issueDate,expiryDate:b.data.expiryDate},...v]);e.currentTarget.reset();setMessage('Certification added.')}
 async function update(id:string,status:string,progress:number){const r=await fetch(`/api/certifications/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,progress})});if(r.ok){const b=await r.json();setItems(v=>v.map(i=>i.id===id?{...i,...b.data}:i))}}
 async function remove(id:string){if(!confirm('Delete this certification?'))return;const r=await fetch(`/api/certifications/${id}`,{method:'DELETE'});if(r.ok)setItems(v=>v.filter(i=>i.id!==id))}
 return <>
  <section className="card" style={{marginBottom:18}}><div className="list-item"><div><h2 style={{marginBottom:5}}>Overall certification progress</h2><span className="muted">Average across your continuous skills ledger</span></div><span className="stat-value">{average}%</span></div><div className="progress"><span style={{width:`${average}%`}}/></div></section>
  <section className="grid grid-3">
   <form className="card form-stack" onSubmit={add}><h2><Plus size={19}/> Add certification</h2>{message&&<div className={`form-message ${message.includes('added')?'success':'error'}`}>{message}</div>}<div className="field"><label>Name</label><input className="input" name="name" required/></div><div className="field"><label>Issuer</label><input className="input" name="issuer" required/></div><div className="form-row"><div className="field"><label>Status</label><select className="select" name="status" defaultValue="IN_PROGRESS"><option value="PLANNED">Planned</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></select></div><div className="field"><label>Progress %</label><input className="input" name="progress" type="number" min="0" max="100" defaultValue="0"/></div></div><div className="field"><label>Skills</label><input className="input" name="skills" placeholder="React, JavaScript"/></div><div className="field"><label>Expiry date (optional)</label><input className="input" name="expiryDate" type="date"/></div><button className="btn btn-primary">Add certification</button></form>
   <div className="grid" style={{gridColumn:'span 2'}}>{items.length?items.map(item=><article className="card" key={item.id}><div className="list-item"><div><span className="icon-box"><Award size={20}/></span><h3 style={{margin:'12px 0 3px'}}>{item.name}</h3><span className="muted">{item.issuer}</span></div><div className="job-actions"><select className="select" value={item.status} onChange={e=>update(item.id,e.target.value,e.target.value==='COMPLETED'?100:item.progress)}><option value="PLANNED">Planned</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option><option value="EXPIRED">Expired</option></select><button className="btn btn-danger btn-small" onClick={()=>remove(item.id)} aria-label="Delete"><Trash2 size={16}/></button></div></div><div className="tags">{item.skills.map(s=><span className="badge" key={s}>{s}</span>)}</div><div style={{display:'flex',gap:12,alignItems:'center',marginTop:14}}><div className="progress" style={{flex:1}}><span style={{width:`${item.progress}%`}}/></div><strong>{item.progress}%</strong></div><input aria-label="Certification progress" type="range" min="0" max="100" value={item.progress} disabled={item.status==='COMPLETED'} onChange={e=>setItems(v=>v.map(i=>i.id===item.id?{...i,progress:Number(e.target.value)}:i))} onMouseUp={e=>update(item.id,item.status,Number((e.target as HTMLInputElement).value))}/></article>):<div className="card empty">No certifications yet. Add the first learning target.</div>}</div>
  </section>
 </>
}
