"use client";
import { FormEvent, useState } from "react";
import { CalendarDays, MapPin, Users, Trophy } from "lucide-react";

type Hack={id:string;name:string;description:string;location:string|null;mode:string;startDate:string;endDate:string;registrationDeadline:string|null;websiteUrl:string|null;technologies:string[];joined:boolean;participants:number;teams:number};
export function HackathonBrowser({initial}:{initial:Hack[]}){
 const [items,setItems]=useState(initial);const [selected,setSelected]=useState('');const [message,setMessage]=useState('');
 async function toggle(id:string,joined:boolean){const r=await fetch(`/api/hackathons/${id}/join`,{method:joined?'DELETE':'POST'});if(r.ok)setItems(v=>v.map(i=>i.id===id?{...i,joined:!joined,participants:i.participants+(joined?-1:1)}:i))}
 async function createTeam(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const payload={hackathonId:selected,name:f.get('name'),description:f.get('description'),repositoryUrl:f.get('repositoryUrl')};const r=await fetch('/api/teams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const b=await r.json();setMessage(r.ok?'Team created.':b.error||'Team could not be created.');if(r.ok){setItems(v=>v.map(i=>i.id===selected?{...i,teams:i.teams+1}:i));e.currentTarget.reset()}}
 return <>
  <section className="grid grid-3">{items.map(h=><article className="card" key={h.id}><span className="icon-box"><Trophy size={21}/></span><h3 style={{marginTop:14}}>{h.name}</h3><div className="tags"><span className="badge gold">{h.mode.replace('_',' ')}</span>{h.technologies.slice(0,3).map(t=><span className="badge" key={t}>{t}</span>)}</div><p className="muted">{h.description}</p><div className="job-meta"><span><MapPin size={14}/>{h.location||'Online'}</span><span><CalendarDays size={14}/>{new Date(h.startDate).toLocaleDateString('en-ZA')} – {new Date(h.endDate).toLocaleDateString('en-ZA')}</span><span><Users size={14}/>{h.participants} joined · {h.teams} teams</span></div><div className="job-actions"><button className={`btn ${h.joined?'btn-secondary':'btn-primary'} btn-small`} onClick={()=>toggle(h.id,h.joined)}>{h.joined?'Leave event':'Join hackathon'}</button>{h.joined&&<button className="btn btn-gold btn-small" onClick={()=>setSelected(h.id)}>Create team</button>}{h.websiteUrl&&<a className="btn btn-secondary btn-small" href={h.websiteUrl} target="_blank">Event website</a>}</div></article>)}</section>
  {selected&&<section className="card" style={{marginTop:18}}><form className="form-stack" onSubmit={createTeam}><div className="list-item"><div><h2>Create a hackathon team</h2><p className="muted">A small shared workspace record will be linked to the selected hackathon.</p></div><button type="button" className="btn btn-secondary btn-small" onClick={()=>setSelected('')}>Close</button></div>{message&&<div className="form-message">{message}</div>}<div className="form-row"><div className="field"><label>Team name</label><input className="input" name="name" required/></div><div className="field"><label>Repository URL</label><input className="input" name="repositoryUrl" type="url" placeholder="https://github.com/..."/></div></div><div className="field"><label>Description</label><textarea className="textarea" name="description"/></div><button className="btn btn-primary">Create team</button></form></section>}
 </>
}
